# DATASOURCE
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://DESKTOP-UILKHHR:2866;databaseName=cursospringboot;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=sql@2019

# Configuraes JPA/Hibernate
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JPA, SQL do BANCO h2 para
#spring.jpa.defer-datasource-initialization=true
#spring.jpa.properties.hibernate.format_sql=true